name: Quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    uses: kemoshumai/typescript-policy/.github/workflows/typescript-quality.yml@cb7fee6313a8caf5ff8695308f6044d7aaa93c5a
