name: Quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    uses: kemoshumai/typescript-policy/.github/workflows/typescript-quality.yml@eaeb52ec096c48ffac0afe7bf407684c8094f99f
